[general]
static=yes
writeprotect=yes
clearglobalvars=no

[lab-internal]
exten => 1000,1,NoOp(call to SIPp UA 1000)
 same => n,Dial(PJSIP/1000,20)
 same => n,Hangup()

exten => 1001,1,NoOp(call to SIPp UA 1001)
 same => n,Dial(PJSIP/1001,20)
 same => n,Hangup()

exten => 9999,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()
