[global]
type=global
user_agent=NGN-Lab-Asterisk
endpoint_identifier_order=username,auth_username,ip

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060

[endpoint-basic](!)
type=endpoint
context=lab-internal
disallow=all
allow=ulaw,alaw
direct_media=no
rtp_symmetric=no
force_rport=no
rewrite_contact=no
timers=no

[auth-userpass](!)
type=auth
auth_type=userpass

[aor-single-reg](!)
type=aor
max_contacts=5
remove_existing=yes
minimum_expiration=60

[1000](endpoint-basic)
auth=1000
aors=1000
callerid="SIPp 1000" <1000>

[1000](auth-userpass)
username=1000
password=1000pass

[1000](aor-single-reg)

[1001](endpoint-basic)
auth=1001
aors=1001
callerid="SIPp 1001" <1001>

[1001](auth-userpass)
username=1001
password=1001pass

[1001](aor-single-reg)
